version: '3'

services:
  # Setup service to ensure ArangoDB is ready
  # This service acts as a coordination point that:
  # 1. Waits for ArangoDB to fully initialize
  # 2. Continuously checks if ArangoDB is responding to requests
  # 3. Only exits successfully after confirming ArangoDB is ready to accept connections
  # 4. Acts as a dependency for the test service, ensuring tests only run when the DB is ready
  setup:
    image: arangodb:3.11
    command: >
      sh -c "
        echo 'Waiting for ArangoDB to start...' &&
        while ! wget -q --spider --user=root --password=password http://arangodb:8529/_api/version; do
          echo 'ArangoDB is not ready yet...'
          sleep 2
        done &&
        echo 'ArangoDB is ready for connections!' &&
        exit 0
      "
    depends_on:
      - arangodb
    networks:
      - test-network

  # ArangoDB service - the database engine
  # This service:
  # 1. Runs the ArangoDB database with appropriate configuration
  # 2. Exposes the default ArangoDB port
  # 3. Sets the root password for authentication
  arangodb:
    image: arangodb:3.11
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    networks:
      - test-network

  # Test service - runs the actual test suite
  # This service:
  # 1. Builds from the Dockerfile.test configuration
  # 2. Depends on the setup service, ensuring ArangoDB is ready before tests start
  # 3. Configures both application and test-specific environment variables
  # 4. Mounts the current directory to allow direct access to the codebase
  # 5. Runs pytest with specific test selections and coverage reporting
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      # Application environment variables
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
      - ARANGO_DB=test_db
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
      - PYTHONPATH=/app
      # Test-specific environment variables
      - TEST_ARANGO_HOST=arangodb
      - TEST_ARANGO_PORT=8529
      - TEST_ARANGO_USER=root
      - TEST_ARANGO_PASSWORD=password
    depends_on:
      - setup
    networks:
      - test-network
    volumes:
      - ./:/app
    command: >
      sh -c "
        echo 'Starting tests...' &&
        cd /app &&
        python -m pytest tests/arango_tests -v &&
        python -m pytest tests/test_database.py tests/test_clear_database.py -v &&
        python -m pytest tests/test_main.py -v --cov=app --cov-report=term-missing
      "

# Shared network to ensure all services can communicate with each other
networks:
  test-network:
    driver: bridge