version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
      - ARANGO_DB=blockchain_intelligence
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
      - LOG_LEVEL=DEBUG
    volumes:
      - ./logs:/app/logs
    depends_on:
      arangodb:
        condition: service_healthy

  arangodb:
    image: arangodb:3.11
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=password
    volumes:
      - ./arangodb/data:/var/lib/arangodb3
      - ./arangodb/apps:/var/lib/arangodb3-apps
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8529"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.6.0
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    volumes:
      - ./logs:/var/log/app:ro
      - ./monitoring/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - app

volumes:
  prometheus_data:
  grafana_data: