version: '3'

services:
  arangodb:
    image: arangodb:3.11
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=password
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps:/var/lib/arangodb3-apps
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8529"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
      - ARANGO_DB=blockchain_intelligence
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
    depends_on:
      arangodb:
        condition: service_healthy

volumes:
  arango_data:
  arango_apps: