version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /data
      - /logs

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testpassword
      - TESTING=1
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - .:/app
      - test-logs:/app/logs
    user: "${UID:-1000}:${GID:-1000}"

volumes:
  test-logs:
